apiVersion: apps/v1
kind: Deployment
metadata:
  name: drf-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drf-app
  template:
    metadata:
      labels:
        app: drf-app
    spec:
      containers:
      - name: drf-app
        image: notification_project-web:latest
        imagePullPolicy: Never 
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_HOST
          value: "postgres-service"
        - name: DATABASE_PORT
          value: "5432"
        - name: DATABASE_NAME
          value: "dbNotification"
        - name: DATABASE_USER
          value: "postgres"
        - name: DATABASE_PASSWORD
          value: "postgres"
        command:
        - "bash"
        - "-c"
        - |
          python manage.py makemigrations && 
          python manage.py migrate && 
          python manage.py runserver 0.0.0.0:8000

---

apiVersion: v1
kind: Service
metadata:
  name: drf-app-service
spec:
  selector:
    app: drf-app  
  ports:
    - protocol: TCP
      port: 80       
      targetPort: 8000  
      nodePort: 30001  
  type: NodePort  